services:
  humhub:
    image: majoryurik/arcdin:latest
    ports:
      - 127.0.0.1:8404:8404
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./humhub-data:/var/lib/humhub
    env_file:
      - ./humhub.env
    environment:
      - HUMHUB_CONFIG__COMPONENTS__DB__DSN=${HUMHUB_DOCKER_DB_DSN}
      - HUMHUB_CONFIG__COMPONENTS__DB__USERNAME=${HUMHUB_DOCKER_DB_USER}
      - HUMHUB_CONFIG__COMPONENTS__DB__PASSWORD=${HUMHUB_DOCKER_DB_PASSWORD}
      - HUMHUB_FIXED_SETTINGS__BASE__BASE_URL=https://${HUMHUB_DOCKER_DOMAIN}
      - HUMHUB_FIXED_SETTINGS__BASE__CACHE_CLASS=yii\redis\Cache
      - HUMHUB_CONFIG__COMPONENTS__REDIS__CLASS=yii\redis\Connection
      - HUMHUB_CONFIG__COMPONENTS__REDIS__HOSTNAME=redis
      - HUMHUB_CONFIG__COMPONENTS__REDIS__PORT=6379
      - HUMHUB_CONFIG__COMPONENTS__REDIS__DATABASE=0
      - HUMHUB_CONFIG__COMPONENTS__SESSION__CLASS=yii\redis\Session
  db:
    image: mariadb
    restart: always
    user: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${HUMHUB_DOCKER_DB_PASSWORD}
    expose:
      - 127.0.0.1:3306:3306
    healthcheck:
      test:  ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect",  "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
    environment:
      - caddydomain=${HUMHUB_DOCKER_DOMAIN}      
    restart: always
  redis:
    image: redis:6.2-alpine
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local